[project]
name = "roblox-multi-client"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "customtkinter>=5.2.2",
    "nuitka>=2.8.9",
    "psutil>=7.2.1",
    "pywin32>=311",
]
